<a href="https://colab.research.google.com/github/heshannana/HIT-140A2/blob/Heshan/HIT_140_A2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
import pandas as pd
import numpy as np

## Exploratory Data Analysis

In [40]:
data = pd.read_csv("/content/fairfield_data.csv", sep = ",", encoding="ISO-8859-1")

In [41]:
data.shape

(122, 12)

In [42]:
data.isna().sum()

Reservoir        0
Fish             0
Mercury          0
Elevation        0
Drainage Area    3
Surface Area     0
Max Depth        1
RF               7
FR               7
Dam              3
RT               1
RS               2
dtype: int64

In [43]:
data.dtypes

Reservoir         object
Fish               int64
Mercury          float64
Elevation          int64
Drainage Area    float64
Surface Area       int64
Max Depth        float64
RF               float64
FR               float64
Dam              float64
RT               float64
RS               float64
dtype: object

In [44]:
data = data.fillna(data.mean())
data.isna().sum()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  """Entry point for launching an IPython kernel.

Reservoir        0
Fish             0
Mercury          0
Elevation        0
Drainage Area    0
Surface Area     0
Max Depth        0
RF               0
FR               0
Dam              0
RT               0
RS               0
dtype: int64

In [45]:
data['Reservoir'].unique()

array(['Abilene', 'Abraham Lake', 'Academy', 'Acadia', 'Acadia Valley',
       'Acheson', 'Acme', 'Adair Creek', 'Adams Creek', 'Bangs Lake',
       'Bank Bay', 'Bank Creek', 'Bankfoot Creek', 'Bankhead', 'Bankview',
       'Bannerman', 'Barnegat', 'Barnes Ridge', 'Barnett Lake',
       'Barnwell', 'Fork Lake', 'Fort Creek', 'Fox Creek', 'Gadois Lake',
       'Gap Creek', 'Gardiner Creek', 'Geikie Lake', 'Geraldine Lakes',
       'Gerard Creek', 'Gertrude Lake', 'Giants Mirror', 'Halach',
       'Halcreek', 'Halfway Creek', 'Halifax Coulee', 'Hamilton Hill',
       'Hamptons', 'Ice Water Creek', 'Junction Creek', 'Jutland Brook',
       'Kakina Lake', 'Kakut Creek', 'Kamisak Lake', 'Katchemut Creek',
       'Kaufmann Creek', 'Keane Creek', 'Keith Lake', 'Owl Lake',
       'Owlseye Lake', 'Oxbow Lake', 'Oxley Creek', 'Pair Lakes',
       'Pans Lake', 'Paradise Basin', 'Paradise Creek', 'Parker Lake',
       'Parlby Lake', 'Parsons Creek', 'Partridge Lake', 'Pasque Creek',
       'Pastecho Lake', 'Plante Creek', 'Plover Lake', 'Poboktan Creek',
       'Poison Creek', 'Pony Creek', 'Popular Point Lake',
       'Stimson Creek', 'Stirling Lake', 'Stones Canyon Creek',
       'Stony Woman Creek', 'Stormy Creek', 'Stouffers Lake',
       'Stove Lake', 'Strawberry Lake', 'Stronach Lake', 'Sturgeon Lake',
       'Swoda Creek', 'Sylvester Creek', 'Tail Creek', 'Talbot Lake',
       'Tamarack Lake', 'Tate Creek', 'Tattum Lake', 'Tawayik Lake',
       'Taylor Lake', 'Telegraph Creek', 'Temple Creek', 'Tepee Creek',
       'Tetley Creek', 'The Snowbowl', 'Thinahtea Creek', 'Third Lake',
       'Thompson Lake', 'Thoreau Creek', 'Two Dam Creek',
       "Two O'Clock Creek", 'Tyler Lake', 'Underwood Lake', 'Updike Lake',
       'Upper Bertha Falls', 'Upper Mann Lake', 'Upper Th√©rien Lake',
       'Utikuma Lake', 'Valhalla Lake', 'Valley Creek', 'Vokes Lake',
       'Volcano Creek', 'Wabash Creek', 'Waddell Creek', 'Wadlin Lake',
       'Wagon Creek', 'Wallaby Lake', 'Wildman Creek', 'Wilson Creek',
       'Winnifred Lake', 'Wood Buffalo Lake', 'Yak Lakes',
       'Yellowstone Creek', 'Zama Lake', 'Zephyr Creek', 'Zig Zag Lake'],
      dtype=object)

In [46]:
data.head()

,Reservoir,Fish,Mercury,Elevation,Drainage Area,Surface Area,Max Depth,RF,FR,Dam,RT,RS
0,Abilene,3,0.053,196,6.0,74,36.0,0.44,1.1,1.0,2.0,0.0
1,Abraham Lake,4,0.350,345,15.0,360,80.0,0.51,1.7,0.0,3.0,1.0
2,Academy,5,0.540,487,1.0,175,10.0,0.57,1.5,0.0,3.0,0.0
3,Acadia,5,0.290,165,131.0,5543,100.0,0.51,1.1,0.0,2.0,1.0
4,Acadia Valley,5,0.910,1273,65.0,700,106.0,0.62,4.3,0.0,1.0,1.0

In [47]:
data = data.drop(['Reservoir'], axis = 1)
data.dtypes

Fish               int64
Mercury          float64
Elevation          int64
Drainage Area    float64
Surface Area       int64
Max Depth        float64
RF               float64
FR               float64
Dam              float64
RT               float64
RS               float64
dtype: object

In [48]:
corr = data.corr()
corr.style.background_gradient(cmap='coolwarm')